cloudflare-project: "aptispace-deeplearning"

project:
  type: book
  output-dir: _site
  pre-render:
    - bash _extensions/aptitek/download-fonts/download_fonts.sh
  post-render: []
  resources:
    - "lab/**"
    - "assets/**"
    - "**/_*.qmd"

bibliography: bibliography.bib

filters:
  - filetree
  - timeline
  - embed

book:
  title: "Deep Learning"
  author: "Aptitek"
  search: false
  site-url: "https://deeplearning.apti.space"

  sidebar:
    logo: "assets/logo.svg"
    logo-href: "/"
    logo-alt: "Aptitek"
    style: "docked"
    search: false

  chapters:
    - index.qmd
    - part: "🎯 Module"
      chapters:
        - meta/module.qmd
        - meta/syllabus.qmd
        - meta/planning.qmd
    # DYNAMIC_CHAPTERS_START
    - part: "🤖 Machine Learning : Les Fondamentaux"
      chapters:
        - cours/1_machine_learning/index.qmd
    - part: "🧠 Réseaux de Neurones Profonds"
      chapters:
        - cours/2_réseaux_de_neurones/index.qmd
    - part: "🔁 Réseaux de Neurones Récurrents (RNN)"
      chapters:
        - cours/3_rnn/index.qmd
    - part: "👁️ Réseaux de Neurones Convolutionnels (CNN)"
      chapters:
        - cours/4_cnn/index.qmd
    - part: "🎲 Autoencodeurs et Modèles Variationnels (VAE)"
      chapters:
        - cours/5_vae/index.qmd
    - part: "⚔️ Modèles Génératifs Antagonistes et Diffusion (GAN)"
      chapters:
        - cours/6_gan/index.qmd
    - part: "🔤 Transformers et Représentations du Langage"
      chapters:
        - cours/7_transformers/index.qmd
    - part: "🚀 LLMs Avancés : Pré-entraînement, Scaling et Alignement"
      chapters:
        - cours/8_avancé/index.qmd
    # DYNAMIC_CHAPTERS_END
    - part: "📝 Projet"
      chapters:
        - project/index.qmd
    - part: "📚 Annexes"
      chapters:
        - glossaire.qmd
        - references.qmd

format:
  html:
    theme:
      - solar
      - .theme/_variables.scss
      - .theme/theme.scss
    mainfont: "Recursive"
    monofont: "Recursive"
    highlight-style: solarized
    code-overflow: wrap
    toc: true
    code-copy: true
    code-tools:
      source: true
      toggle: false
      caption: "Voir le code source"
    mermaid:
      theme: neutral
    html-math-method: katex
    number-sections: true
    header-includes: |
      <meta name="robots" content="noindex, nofollow">
    include-in-header:
      - text: '<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>'
      - text: |
          <script type="module">
            if (!window.aptitek) {
              const mod = await import("/assets/js/index.js");
              window.aptitek = Object.freeze({ ...mod });
            }
          </script>
    include-after-body: assets/fix_links.html
    css: .theme/book_custom.css
